- build.gradle
- src/main/java/com/hanghae/bulletbox/common/security/UserDetailsServiceImpl.java
- src/main/java/com/hanghae/bulletbox/common/security/jwt/JwtUtil.java
* 시큐리티 의존성 주입
* 패키지 경로가 잘못 설정되어 있어, 재설정
- build.gradle에 시큐리티 의존성 주입
- UserDetailsServiceImpl 클래스의 package com.hanghae.bulletbox.common.security.jwt; 로 설정되어 있던 경로를 package com.hanghae.bulletbox.common.security 로 변경
close #3
> 🐛 Fix: 패키지 경로 재설정 및 시큐리티 의존성 주입

- src/main/java/com/hanghae/bulletbox/common/response/Response.java
Response 설정
- Response 설정
close #6
> ✨ Feat: Response 설정

- .github/workflows/ci.yml
> 📝 doc: git actions CI 적용

- src/main/java/com/hanghae/bulletbox/common/exception/ExceptionMessage.java
- src/main/java/com/hanghae/bulletbox/member/controller/MemberController.java
- src/main/java/com/hanghae/bulletbox/member/dto/LoginDto.java
- src/main/java/com/hanghae/bulletbox/member/dto/RequestLoginDto.java
- src/main/java/com/hanghae/bulletbox/member/mapper/MemberMapper.java
- src/main/java/com/hanghae/bulletbox/member/service/MemberService.java
로그인 API 구현
- 로그인 API 구현
- 이메일 인증 구현 목표
close #9 
> ✨ Feat : 로그인 API 구현

- .github/workflows/ci-cd.yml
- appspec.yml
- build.gradle
- scripts/start.sh
- scripts/stop.sh
Git Actions를 이용해 CD를 적용했습니다.
1. AWS 연결을 위한 appspec.yml 파일 작성
2. 파일이 배포되면 서버를 종료하고 다시 시작하기 위한 스크립트 파일들 scripts 디렉토리 안에 작성
3. Git Actions CD 를 실행할 ci-cd.yml 파일 작성 
close #18
> 📝 docs: CD 적용

- src/main/java/com/hanghae/bulletbox/category/dto/CategoryDto.java
- src/main/java/com/hanghae/bulletbox/category/entity/Category.java
- src/main/java/com/hanghae/bulletbox/category/repository/CategoryRepository.java
- src/main/java/com/hanghae/bulletbox/diary/controller/MainController.java
- src/main/java/com/hanghae/bulletbox/diary/dto/CalendarDto.java
- src/main/java/com/hanghae/bulletbox/diary/dto/DailyDto.java
- src/main/java/com/hanghae/bulletbox/diary/dto/ResponseMainDto.java
- src/main/java/com/hanghae/bulletbox/diary/service/MainService.java
- src/main/java/com/hanghae/bulletbox/todo/TodoBullet.java
- src/main/java/com/hanghae/bulletbox/todo/repository/MemoRepository.java
- src/main/java/com/hanghae/bulletbox/todo/repository/TodoRepository.java
메인 페이지 조회 API 구현
- 메인 페이지 조회를 위한 Controller, Service 로직 구현 및 Dto 생성
close #14 
아직 데이터가 존재하지 않아, 응답 결과가 성공한 것으로 이미지 업로드.
> ✨ Feat: 메인 페이지 조회 API 구현

- scripts/start.sh
- scripts/stop.sh
CodeDeploy에 필요한 Script 파일에서 경로 설정이 잘못 되어 있어서 오류가 났습니다. 해당 부분 수정했습니다.
close #21
> 🐛 fix: Codedeploy용 scipts 파일 수정

- .github/workflows/ci-cd.yml
- .github/workflows/ci.yml
메일 인증에 필요한 secret 내용들을 CI/CD 파일에 적어 두었습니다.
close #24
> ✨ feat: 메일 인증에 필요한 secret 내용 CI/CD에 포함

- .github/workflows/ci-cd.yml
- .github/workflows/ci.yml
- .gitignore
- build.gradle
- src/main/resources/application.properties
RDS MySQL에 연결하는 작업을 진행했습니다. 테이블 생성까지 완료해 두었습니다.
close #28
> 🔧 chore: MySQL RDS 연결

- src/main/java/com/hanghae/bulletbox/common/config/WebSecurityConfig.java
Security config 에서 h2 관련 내용 삭제
close #32
> 🐛 fix: Security config 수정

- .gitignore
- src/main/java/com/hanghae/bulletbox/common/exception/ExceptionMessage.java
- src/main/java/com/hanghae/bulletbox/diary/controller/MainController.java
- src/main/java/com/hanghae/bulletbox/diary/dto/ResponseChangeCalendarDto.java
- src/main/java/com/hanghae/bulletbox/diary/service/MainService.java
- src/main/java/com/hanghae/bulletbox/todo/repository/TodoRepository.java
메인 페이지 내 달력 조회 날짜 변경 API 구현
- 사용자 검증 시, 해당 사용자가 없을 경우 에러 메시지를 ExceptionMessage에 추가
- 해당 API 구현을 위한 컨트롤러 추가
- 해당 API를 구현하기 위한 changeCalendar 서비스 로직 구현
- changeCalendar 의 응답을 위한 ResponseChangeCalendarDto 생성
close #27 
데이터가 존재하지 않아, response 로 대체.
> ✨ Feat: 메인 페이지 내 달력 조회 날짜 변경 API 구현

- src/main/java/com/hanghae/bulletbox/common/config/WebSecurityConfig.java
- src/main/java/com/hanghae/bulletbox/member/dto/RequestSignupDto.java
패스워드 정규식 수정 및 localhost 수정
- 패스워드 정규식 수정 및 localhost 수정
> ♻️ Refactor : 패스워드 정규식 수정 및 localhost 수정

- src/main/java/com/hanghae/bulletbox/diary/service/MainService.java
메인 페이지 조회 시, 달력의 날짜를 현재 연, 월로 설정
- 메인 페이지 조회 시, 달력의 날짜를 현재 연, 월로 설정
- Exception 처리
close #31 
데이터가 존재하지 않아, response 로 대체
> ♻️ Refactor: 메인 페이지 조회 시, 달력의 날짜를 현재 연, 월로 설정

- src/main/java/com/hanghae/bulletbox/diary/service/MainService.java
사용하지 않는 import 삭제
- 사용하지 않는 import 삭제
close #31
> 🔧 Chore: 사용하지 않는 import 삭제

- src/main/java/com/hanghae/bulletbox/todo/dto/TodoDto.java
TodoDto 생성
- TodoDto 생성
close #46
> ✨ Feat: TodoDto 생성

- src/main/java/com/hanghae/bulletbox/todo/dto/TodoDto.java
TodoDto Builder 패턴 private 적용
- @Builder 를 Delombok 하여 private 적용
close #48
> ♻️ Refactor: TodoDto Builder 패턴 private 적용

- src/main/java/com/hanghae/bulletbox/diary/controller/DailyController.java
- src/main/java/com/hanghae/bulletbox/diary/dto/ResponseDailyDto.java
- src/main/java/com/hanghae/bulletbox/diary/service/DailyService.java
- src/main/java/com/hanghae/bulletbox/todo/entity/Memo.java
- src/main/java/com/hanghae/bulletbox/todo/entity/Todo.java
- src/main/java/com/hanghae/bulletbox/todo/repository/TodoRepository.java
Daily 로그 조회 API 구현
- Daily log 조회 구현
- 불필요한 Builder 삭제
close #26 
> ✨ Feat : Daily 로그 조회 API 구현

- src/main/java/com/hanghae/bulletbox/diary/controller/MainController.java
- src/main/java/com/hanghae/bulletbox/diary/dto/ResponseShowDailyDto.java
- src/main/java/com/hanghae/bulletbox/diary/service/MainService.java
데일리 로그 조회 날짜 변경
- 데일리 로그 조회 날짜 변경
close #40 
데이터 값이 없어, 응답으로 대체
> ✨ Feat: 데일리 로그 조회 날짜 변경 API 구현

- src/main/java/com/hanghae/bulletbox/category/dto/ResponseCategoryDto.java
- src/main/java/com/hanghae/bulletbox/diary/controller/DailyController.java
- src/main/java/com/hanghae/bulletbox/diary/service/DailyService.java
- src/main/java/com/hanghae/bulletbox/todo/repository/TodoRepository.java
데일리 로그 카테고리 별 조회 API 구현
- 데일리 로그 카테고리 별 조회 API 구현
close #51
> ✨ Feat : 데일리 로그 카테고리 별 조회 API 구현

- src/main/java/com/hanghae/bulletbox/diary/controller/MainController.java
- src/main/java/com/hanghae/bulletbox/diary/dto/ResponseShowDailyByCategoryDto.java
- src/main/java/com/hanghae/bulletbox/diary/service/MainService.java
- src/main/java/com/hanghae/bulletbox/todo/dto/TodoDto.java
- src/main/java/com/hanghae/bulletbox/todo/repository/TodoRepository.java
메인 페이지 카테고리별 데일리 로그 조회 API 구현
- 해당 API 구현을 위한 메서드 컨트롤러에 추가
- 해당 API 구현을 위한 서비스 로직 구현
- 해당 API 서비스 로직의 응답을 위한 Dto 생성
- TodoDto의 Builder 패턴 수정
close #53 
데이터 값이 존재하지 않아, 응답 성공으로 대체
> ✨ Feat: 메인 페이지 카테고리별 데일리 로그 조회 API 구현

- src/main/java/com/hanghae/bulletbox/member/controller/MemberController.java
이메일 인증 controller 로직 수정
- param -> body로 수정
close #56
> ♻️ Refactor : 이메일 인증 controller 로직 수정

- src/main/java/com/hanghae/bulletbox/diary/controller/DailyController.java
- src/main/java/com/hanghae/bulletbox/diary/service/DailyService.java
- src/main/java/com/hanghae/bulletbox/todo/repository/TodoRepository.java
데일리 로그 카테고리별 조회 API 수정
- locadate가 아닌 todo값 가져오는걸로 수정
- repository에서 member 추가
close #61
> ♻️ Refactor : 데일리 로그 카테고리별 조회 API 수정

- src/main/java/com/hanghae/bulletbox/diary/controller/DailyController.java
- src/main/java/com/hanghae/bulletbox/diary/service/DailyService.java
- src/main/java/com/hanghae/bulletbox/member/controller/MemberController.java
데일리로그 조회 날짜 변경 controller, service 로직 추가
- 데일리로그 조회 날짜 변경 controller, service 로직 추가
closed #62
> ✨ Feat : 데일리로그 조회 날짜 변경 API구현

- src/main/java/com/hanghae/bulletbox/common/exception/GlobalExceptionHandler.java
- src/main/java/com/hanghae/bulletbox/common/response/Response.java
- src/main/java/com/hanghae/bulletbox/member/controller/MemberController.java
이메일인증 예외처리 refactor
- 이메일인증 예외처리 refactor
> ♻️ Refactor : 이메일인증 예외처리 refactor

- src/main/java/com/hanghae/bulletbox/member/controller/MemberController.java
equals 변수 순서 변경
- equals 변수 순서 변경
> ♻️ Refactor : equals 변수 순서 변경

- build.gradle
- src/main/java/com/hanghae/bulletbox/common/config/SwaggerConfig.java
- src/main/java/com/hanghae/bulletbox/common/config/WebSecurityConfig.java
- src/main/java/com/hanghae/bulletbox/common/response/Response.java
- src/main/java/com/hanghae/bulletbox/diary/controller/DailyController.java
- src/main/java/com/hanghae/bulletbox/diary/controller/MainController.java
- src/main/java/com/hanghae/bulletbox/diary/dto/CalendarDto.java
- src/main/java/com/hanghae/bulletbox/diary/dto/DailyDto.java
- src/main/java/com/hanghae/bulletbox/diary/dto/ResponseDailyDto.java
- src/main/java/com/hanghae/bulletbox/diary/dto/ResponseShowCalendarDto.java
- src/main/java/com/hanghae/bulletbox/diary/dto/ResponseShowDailyByCategoryDto.java
- src/main/java/com/hanghae/bulletbox/diary/dto/ResponseShowDailyDto.java
- src/main/java/com/hanghae/bulletbox/diary/dto/ResponseShowMainPageDto.java
- src/main/java/com/hanghae/bulletbox/member/controller/MemberController.java
- src/main/java/com/hanghae/bulletbox/member/dto/MemberDto.java
- src/main/java/com/hanghae/bulletbox/member/dto/RequestLoginDto.java
- src/main/java/com/hanghae/bulletbox/member/dto/RequestSignupDto.java
- src/main/java/com/hanghae/bulletbox/member/dto/VerifyCodeDto.java
- src/main/java/com/hanghae/bulletbox/todo/dto/TodoDto.java
- src/main/resources/application.properties
Swagger 적용
- Swagger Config 파일 추가
- 모든 Dto, Controller 에 Swagger 적용
closed #69
> ✨ Feat: Swagger 적용

- src/main/java/com/hanghae/bulletbox/common/config/SwaggerConfig.java
SwaggerConfig ApiKey의 name, keyname 값이 매칭되지 않는 에러
- name과 keyname의 값을 동일하게 변경
closed #75
> 🐛 Fix: SwaggerConfig ApiKey의 name, keyname 값이 매칭되지 않는 에러

- src/main/java/com/hanghae/bulletbox/category/controller/CategoryController.java
- src/main/java/com/hanghae/bulletbox/category/dto/CategoryDto.java
- src/main/java/com/hanghae/bulletbox/category/dto/ResponseShowCategoryDto.java
- src/main/java/com/hanghae/bulletbox/category/service/CategoryService.java
카테고리 목록 조회 API 구현
- CategoryDto 내 memberId를 인자로 받는 정적 팩토리 메서드 추가
- CategoryController에 카테고리 목록 조회를 위한 메서드 추가
- 카테고리 목록 조회 서비스 로직 구현
- 카테고리 목록 조회 응답 DTO 생성
closed #79
> ✨ Feat: 카테고리 목록 조회 API 구현

- src/main/java/com/hanghae/bulletbox/category/service/CategoryService.java
- src/main/java/com/hanghae/bulletbox/diary/controller/DailyController.java
- src/main/java/com/hanghae/bulletbox/diary/dto/DailyDto.java
- src/main/java/com/hanghae/bulletbox/diary/dto/DailyTodoDto.java
- src/main/java/com/hanghae/bulletbox/diary/dto/ResponseShowTodoCreatePageDto.java
- src/main/java/com/hanghae/bulletbox/diary/service/DailyService.java
- src/main/java/com/hanghae/bulletbox/diary/service/DailyTodoService.java
- src/main/java/com/hanghae/bulletbox/diary/service/MainService.java
- src/main/java/com/hanghae/bulletbox/member/dto/MemberDto.java
- src/main/java/com/hanghae/bulletbox/todo/MemoBullet.java
- src/main/java/com/hanghae/bulletbox/todo/dto/TodoMemoDto.java
- src/main/java/com/hanghae/bulletbox/todo/entity/TodoMemo.java
- src/main/java/com/hanghae/bulletbox/todo/repository/TodoMemoRepository.java
데일리 로그 할일 추가 페이지를 조회하는 API를 구현하였습니다.
- CategoryRepository에 접하는 CategoryService 생성
- 응답에 필요한 Dto 생성
- DailyController, DailyTodoService에 필요한 메소드 구현
close #78
> ✨ feat: 데일리 로그 할일 추가 페이지 조회 API 구현

- src/main/java/com/hanghae/bulletbox/category/controller/CategoryController.java
- src/main/java/com/hanghae/bulletbox/category/dto/CategoryDto.java
- src/main/java/com/hanghae/bulletbox/category/dto/RequestUpdateCategoryDto.java
- src/main/java/com/hanghae/bulletbox/category/entity/Category.java
- src/main/java/com/hanghae/bulletbox/category/repository/CategoryRepository.java
- src/main/java/com/hanghae/bulletbox/category/service/CategoryPageService.java
- src/main/java/com/hanghae/bulletbox/common/exception/ExceptionMessage.java
- src/main/java/com/hanghae/bulletbox/diary/service/MainService.java
- src/main/java/com/hanghae/bulletbox/member/dto/RequestLoginDto.java
특정 카테고리 수정 API 구현
- 카테고리 수정 API를 컨트롤러에 추가
- CategoryDto 정적 팩토리 메서드 추가 및 Schema 어노테이션 추가
- Category Entity에 업데이트 메서드 추가
- Category 레포지토리에 Member, categoryId를 기준으로 Category 조회하는 메서드 추가
- 카테고리 수정 API 서비스 로직 구현
- ExceptionMessage 카테고리 유효성 검사에 대한 익셉션 메시지 추가
- MainService Transactional 어노테이션 추가
- RequsetLoginDto Schema 어노테이션의 example 프로퍼티 수정
close #83
> ✨ Feat: 특정 카테고리 수정 API 구현

- src/main/java/com/hanghae/bulletbox/category/controller/CategoryController.java
- src/main/java/com/hanghae/bulletbox/category/dto/ResponseCreateCategoryDto.java
- src/main/java/com/hanghae/bulletbox/category/service/CategoryPageService.java
카테고리 생성 API 수정
- 컨트롤러에서 카테고리 생성 API의 리턴값 추가(ResponseCreateCategoryDto)
- ResponseCreateCategoryDto 응답 DTO 생성
- 카테고리 생성 API의 서비스 로직 리턴값 추가
- 컨트롤러에서 showCategory 메서드의 반환타입 제네릭 수정
close #90
> ♻️ Refactor: 카테고리 생성 API 수정

- src/main/java/com/hanghae/bulletbox/favorite/entity/Favorite.java
- src/main/java/com/hanghae/bulletbox/member/dto/MemberDto.java
- src/main/java/com/hanghae/bulletbox/member/dto/RequestSignupDto.java
- src/main/java/com/hanghae/bulletbox/member/entity/Member.java
- src/main/java/com/hanghae/bulletbox/member/service/MemberService.java
- src/main/java/com/hanghae/bulletbox/todo/dto/TodoDto.java
- src/main/java/com/hanghae/bulletbox/todo/entity/Todo.java
전체 코드 리팩토링
- 전체 코드 리팩토링
close #92
> ♻️ Refactor: 전체 코드 리팩토링

- src/main/java/com/hanghae/bulletbox/common/config/WebSecurityConfig.java
SecurityConfig 프론트 도메인 추가
- SecurityConfig 프론트 도메인 추가
close #94
> ✨ Feat : SecurityConfig 프론트 도메인 추가

- src/main/java/com/hanghae/bulletbox/mypage/controller/MyPageController.java
- src/main/java/com/hanghae/bulletbox/mypage/dto/MyPageDto.java
- src/main/java/com/hanghae/bulletbox/mypage/dto/ResponseShowMyPageDto.java
- src/main/java/com/hanghae/bulletbox/mypage/service/MyPageService.java
마이 페이지 조회 API 구현
- 마이 페이지 조회 API 컨트롤러에 추가
- MyPageDto 마이 페이지 조회 API의 서비스 범용 DTO 생성
- ResponseShowMyPageDto 마이 페이지 조회 API 응답 DTO 생성
- 마이 페이지 조회 API 서비스 로직 구현
close #96
> ✨ Feat: 마이 페이지 조회 API 구현

- src/main/java/com/hanghae/bulletbox/category/service/CategoryService.java
- src/main/java/com/hanghae/bulletbox/common/exception/ExceptionMessage.java
- src/main/java/com/hanghae/bulletbox/common/exception/GlobalExceptionHandler.java
- src/main/java/com/hanghae/bulletbox/diary/controller/DailyController.java
- src/main/java/com/hanghae/bulletbox/diary/controller/MainController.java
- src/main/java/com/hanghae/bulletbox/diary/dto/DailyTodoDto.java
- src/main/java/com/hanghae/bulletbox/diary/dto/RequestCreateTodoDto.java
- src/main/java/com/hanghae/bulletbox/diary/service/DailyService.java
- src/main/java/com/hanghae/bulletbox/diary/service/DailyTodoService.java
- src/main/java/com/hanghae/bulletbox/diary/service/MainService.java
- src/main/java/com/hanghae/bulletbox/member/dto/MemberDto.java
- src/main/java/com/hanghae/bulletbox/member/entity/Member.java
- src/main/java/com/hanghae/bulletbox/todo/TodoBullet.java
- src/main/java/com/hanghae/bulletbox/todo/dto/TodoDto.java
- src/main/java/com/hanghae/bulletbox/todo/dto/TodoMemoDto.java
- src/main/java/com/hanghae/bulletbox/todo/entity/Todo.java
- src/main/java/com/hanghae/bulletbox/todo/entity/TodoMemo.java
- src/main/java/com/hanghae/bulletbox/todo/service/TodoMemoService.java
- src/main/java/com/hanghae/bulletbox/todo/service/TodoService.java
데일리 로그에서 할 일을 추가하는 API를 구현하였습니다. 구현 과정에서 다른 코드를 리팩토링 할 필요가 있어서 리팩토링 작업을 같이 진행하였습니다.
- Entity를 멤버변수로 사용하는 모든 DTO 수정
- 해당 수정으로 인해 오류가 생긴 로직들 수정
- Entity와 Entity를 대체하는 DTO 사이의 변환 로직 생성
- 할 일 저장하는 로직 생성
close #36
> ✨ feat: 할 일 추가 API 구현

- src/main/java/com/hanghae/bulletbox/common/entity/TimeStamped.java
- src/main/java/com/hanghae/bulletbox/todo/entity/Todo.java
- src/main/java/com/hanghae/bulletbox/todo/entity/TodoMemo.java
메인 페이지 조회 시 500 에러가 났는데, 로그를 살펴보니 Lazy 로딩으로 proxy로 불려온 엔티티를 Jackson으로 반환할 때 생기는 오류였습니다. 
제일 좋은 방법은 엔티티를 직접 반환하지 않고 DTO로 묶어서 반환하는 것이지만, 리팩토링에 시간이 걸려서 급한 대로 문제가 되는 엔티티 필드들에 JsonIgnore를 적용하여서 해결하였습니다.
close #100
> 🐛 fix: 메인페이지 조회 시 오류 수정

- src/main/java/com/hanghae/bulletbox/BulletBoxApplication.java
- src/main/java/com/hanghae/bulletbox/common/entity/TimeStamped.java
LocalDateTime 사용 시, UTC로 적용되는 오류 수정
- @JsonFormat 어노테이션을 사용해 KST 설정
close #107
> 🐛 Fix: LocalDateTime 사용 시, UTC로 적용되는 오류 수정

- src/main/java/com/hanghae/bulletbox/category/repository/CategoryRepository.java
- src/main/java/com/hanghae/bulletbox/common/exception/ExceptionMessage.java
- src/main/java/com/hanghae/bulletbox/todo/repository/TodoRepository.java
- src/main/java/com/hanghae/bulletbox/todo/service/TodoMemoService.java
- src/main/java/com/hanghae/bulletbox/todo/service/TodoService.java
할 일 저장시 null값 메모가 저장되는 오류를 수정했습니다. memo 내용이 null일 시 메모를 저장하지 않도록 했습니다.
- Todo 저장 시 유효성 검사 적용
- TodoMemo 저장 시 유효성 검사 적용
close #106
> 🐛 fix: 할 일 저장시 null값 메모가 저장되는 오류 수정

- src/main/java/com/hanghae/bulletbox/diary/controller/DailyController.java
- src/main/java/com/hanghae/bulletbox/diary/dto/DailyTodoDto.java
- src/main/java/com/hanghae/bulletbox/diary/service/DailyTodoService.java
- src/main/java/com/hanghae/bulletbox/todo/repository/TodoMemoRepository.java
- src/main/java/com/hanghae/bulletbox/todo/service/TodoMemoService.java
- src/main/java/com/hanghae/bulletbox/todo/service/TodoService.java
할 일을 삭제하는 API를 구현하였습니다. Cascade를 사용하지 않기 때문에 하위 할 일 메모를 삭제한 후 할 일을 삭제하였습니다.
- 할 일 메모 삭제 로직 구현
- 할 일 삭제 로직 구현
close #43
> ✨ feat: 할일 삭제 API 구현

- src/main/java/com/hanghae/bulletbox/todo/service/TodoService.java
할 일 작성할 때 카테고리가 없으면 저장이 안되는 오류 수정하였습니다. categoryId가 null 일 때의 처리가 없어서 발생했던 오류였습니다. 
close #113
> 🐛 fix: 할 일 작성할 때 카테고리가 없으면 나오던 오류 수정

- build.gradle
- src/main/java/com/hanghae/bulletbox/common/config/MailConfig.java
- src/main/java/com/hanghae/bulletbox/common/config/RedisConfig.java
- src/main/java/com/hanghae/bulletbox/common/exception/ExceptionMessage.java
- src/main/java/com/hanghae/bulletbox/common/redis/RedisUtil.java
- src/main/java/com/hanghae/bulletbox/member/controller/MemberController.java
- src/main/java/com/hanghae/bulletbox/member/service/MailService.java
- src/main/resources/application.properties
Redis 적용
- 이메일 인증 시 레디스를 통해 저장 후 인증하도록 변경
- 이메일 인증번호 유효시간 5분으로 변경
close #98
> ✨ Feat : Redis 적용

- src/main/java/com/hanghae/bulletbox/common/config/SwaggerConfig.java
- src/main/java/com/hanghae/bulletbox/common/exception/ExceptionMessage.java
- src/main/java/com/hanghae/bulletbox/favorite/controller/FavoriteController.java
- src/main/java/com/hanghae/bulletbox/favorite/dto/FavoriteDto.java
- src/main/java/com/hanghae/bulletbox/favorite/dto/FavoriteMemoDto.java
- src/main/java/com/hanghae/bulletbox/favorite/dto/FavoritePageDto.java
- src/main/java/com/hanghae/bulletbox/favorite/dto/RequestCreateFavoriteTodoDto.java
- src/main/java/com/hanghae/bulletbox/favorite/dto/ResponseCreateFavoriteTodoDto.java
- src/main/java/com/hanghae/bulletbox/favorite/entity/Favorite.java
- src/main/java/com/hanghae/bulletbox/favorite/entity/FavoriteMemo.java
- src/main/java/com/hanghae/bulletbox/favorite/repository/FavoriteRepository.java
- src/main/java/com/hanghae/bulletbox/favorite/service/FavoriteMemoService.java
- src/main/java/com/hanghae/bulletbox/favorite/service/FavoritePageService.java
- src/main/java/com/hanghae/bulletbox/favorite/service/FavoriteService.java
자주 쓰는 할 일 생성 API 구현
-  자주 쓰는 할 일 에러 메시지 추가
- FavoriteController 자주 쓰는 할 일 API의 컨트롤러 생성
- FavoriteDto 자주 쓰는 할 일 Dto 생성
- FavoriteMemoDto 자주 쓰는 할 일의 메모 Dto 생성
- FavoritePageDto 자주 쓰는 할 일의 서비스 Dto 생성
- RequestCreateFavoriteTodoDto 자주 쓰는 할 일 생성 API의 요청 Dto 생성
- ResponseCreateFavoriteTodoDto 자주 쓰는 할 일 생성 API의 응답 Dto 생성
- Favorite, FavoriteMemo Entity 변환 정적 팩토리 메서드 추가
- FavoriteRepository favoriteId, Member 기준으로 할 일 조회하는 JPA 메서드 추가
- FavoriteMemoService 자주 쓰는 할 일의 메모 클래스가 레포지토리에 의존하는 서비스 클래스 생성
- FavoritePageService 자주 쓰는 할 일 생성 API 서비스 로직 구현
- FavoriteService 자주 쓰는 할 일 클래스가 레포지토리에 의존하는 서비스 클래스 생성
close #117
> ✨ Feat: 자주 쓰는 할 일 생성 API 구현

- src/main/java/com/hanghae/bulletbox/diary/controller/DailyController.java
- src/main/java/com/hanghae/bulletbox/diary/dto/DailyTodoDto.java
- src/main/java/com/hanghae/bulletbox/diary/dto/ResponseTodoUpdatePageDto.java
- src/main/java/com/hanghae/bulletbox/diary/service/DailyTodoService.java
- src/main/java/com/hanghae/bulletbox/todo/dto/TodoDto.java
- src/main/java/com/hanghae/bulletbox/todo/dto/TodoMemoDto.java
- src/main/java/com/hanghae/bulletbox/todo/service/TodoMemoService.java
데일리로그 수정 페이지를 조회하는 API를 구현하였습니다.
- 필요한 Dto 생성 및 수정
- 필요한 로직들 구현
close #42
> ✨ feat: 데일리로그 수정 페이지 조회 API 구현

- src/main/java/com/hanghae/bulletbox/favorite/service/FavoritePageService.java
Transactional 어노테이션 붙이기
- 자주 쓰는 할 일 API 서비스 로직 메서드에 Transactional 어노테이션 붙임.
close #123
> ♻️ Refactor: Transactional 어노테이션 붙이기

- src/main/java/com/hanghae/bulletbox/diary/service/DailyService.java
- src/main/java/com/hanghae/bulletbox/diary/service/MainService.java
동일한 로직 사용하던 모든 로직들 수정
메인 페이지와 데일리 로그 조회 시 메모 없는 할 일이 조회 되지 않는 문제가 있었습니다. 해당 부분 로직 수정하여 해결하였습니다.
close #129
> 🐛 fix: 데일리 로그 조회 로직 수정

- src/main/java/com/hanghae/bulletbox/diary/service/DailyService.java
데일리 로그 조회 시 categoryColor가 출력되지 않는 오류 수정
- categoryColor를 초기화 시켜줌으로써 해결.
close #133
> fix: 데일리 로그 조회 시 categoryColor가 출력되지 않는 오류 수정

- src/main/java/com/hanghae/bulletbox/favorite/controller/FavoriteController.java
- src/main/java/com/hanghae/bulletbox/favorite/dto/FavoriteDto.java
- src/main/java/com/hanghae/bulletbox/favorite/dto/FavoritePageDto.java
- src/main/java/com/hanghae/bulletbox/favorite/repository/FavoriteMemoRepository.java
- src/main/java/com/hanghae/bulletbox/favorite/repository/FavoriteRepository.java
- src/main/java/com/hanghae/bulletbox/favorite/service/FavoriteMemoService.java
- src/main/java/com/hanghae/bulletbox/favorite/service/FavoritePageService.java
- src/main/java/com/hanghae/bulletbox/favorite/service/FavoriteService.java
자주 쓰는 할 일 삭제 API 구현
- favoriteMemo의 존재여부에 따른 분기문 작성
- 해당 API 구현에 필요한 서비스 로직 구현 및 컨트롤러 추가
- 해당 API 구현에 필요한 정적 팩토리 메서드를 Dto에 추가
- 해당 API 구현에 필요한 JPA 메서드 추가  
close #119
> ✨ Feat: 자주 쓰는 할 일 삭제 API 구현

- src/main/java/com/hanghae/bulletbox/common/exception/ExceptionMessage.java
- src/main/java/com/hanghae/bulletbox/diary/controller/DailyController.java
- src/main/java/com/hanghae/bulletbox/diary/dto/DailyTodoDto.java
- src/main/java/com/hanghae/bulletbox/diary/dto/RequestUpdateTodoDto.java
- src/main/java/com/hanghae/bulletbox/diary/service/DailyTodoService.java
- src/main/java/com/hanghae/bulletbox/todo/dto/TodoDto.java
- src/main/java/com/hanghae/bulletbox/todo/entity/Todo.java
- src/main/java/com/hanghae/bulletbox/todo/entity/TodoMemo.java
- src/main/java/com/hanghae/bulletbox/todo/service/TodoMemoService.java
- src/main/java/com/hanghae/bulletbox/todo/service/TodoService.java
할 일을 수정하는 API를 구현하였습니다. 할 일 수정 시 들어온 메모가 삭제된 건지, 수정된 건지, 새로 생긴 건지 구분해서 각각 필요한 쿼리를 날리도록 하였습니다.
close #41
> ✨ feat: 데일리 로그 할 일 수정 API 구현

- src/main/java/com/hanghae/bulletbox/common/exception/ExceptionMessage.java
- src/main/java/com/hanghae/bulletbox/favorite/controller/FavoriteController.java
- src/main/java/com/hanghae/bulletbox/favorite/dto/FavoriteDto.java
- src/main/java/com/hanghae/bulletbox/favorite/dto/FavoritePageDto.java
- src/main/java/com/hanghae/bulletbox/favorite/dto/RequestUpdateFavoriteTodoDto.java
- src/main/java/com/hanghae/bulletbox/favorite/entity/Favorite.java
- src/main/java/com/hanghae/bulletbox/favorite/entity/FavoriteMemo.java
- src/main/java/com/hanghae/bulletbox/favorite/repository/FavoriteMemoRepository.java
- src/main/java/com/hanghae/bulletbox/favorite/repository/FavoriteRepository.java
- src/main/java/com/hanghae/bulletbox/favorite/service/FavoriteMemoService.java
- src/main/java/com/hanghae/bulletbox/favorite/service/FavoritePageService.java
- src/main/java/com/hanghae/bulletbox/favorite/service/FavoriteService.java
루틴 수정 API 로직 구현
- dirtychecking 을 통한 루틴 수정 API 로직 구현
close #118
> ✨ Feat: 루틴 수정 API 로직 구현

- src/main/java/com/hanghae/bulletbox/BulletBoxApplication.java
LocalDateTime KST 설정
- main 클래스에 LocalDateTime KST 설정
close #107
> 🐛 Fix: LocalDateTime KST 설정

- src/main/java/com/hanghae/bulletbox/todo/controller/TodoController.java
- src/main/java/com/hanghae/bulletbox/todo/dto/ResponseSearchTodoDto.java
- src/main/java/com/hanghae/bulletbox/todo/dto/SearchPageDto.java
- src/main/java/com/hanghae/bulletbox/todo/dto/SearchTodoDto.java
- src/main/java/com/hanghae/bulletbox/todo/dto/TodoMemoDto.java
- src/main/java/com/hanghae/bulletbox/todo/entity/Todo.java
- src/main/java/com/hanghae/bulletbox/todo/repository/TodoRepository.java
- src/main/java/com/hanghae/bulletbox/todo/service/SearchTodoService.java
- src/main/java/com/hanghae/bulletbox/todo/service/TodoMemoService.java
- src/main/java/com/hanghae/bulletbox/todo/service/TodoService.java
할 일 검색 API 구현
- 할 일 검색 API를 위한 Dto 생성
- 할 일 검색 API를 위한 컨트롤러, 서비스 로직 구현
- requestParam으로 넘어온 요청 값을 contains를 이용해 비교 진행.
close #145
> ✨ Feat: 할 일 검색 API 구현

- src/main/java/com/hanghae/bulletbox/diary/dto/DailyTodoDto.java
할 일 수정 페이지 조회 시 categoryColor 값 추가
close #147
> ✨ feat: 할 일 수정 페이지 조회 시 categoryColor 값 추가

- .github/workflows/ci-cd.yml
- .github/workflows/ci.yml
- .gitignore
- build.gradle
- src/main/java/com/hanghae/bulletbox/common/exception/ExceptionMessage.java
- src/main/java/com/hanghae/bulletbox/common/security/jwt/JwtAuthenticationFilter.java
- src/main/java/com/hanghae/bulletbox/common/security/jwt/JwtUtil.java
- src/main/java/com/hanghae/bulletbox/member/controller/MemberController.java
- src/main/java/com/hanghae/bulletbox/member/dto/VerifyCodeDto.java
- src/main/java/com/hanghae/bulletbox/member/service/MemberService.java
RefreshToken 구현
- RefreshToken 구현
- Redis를 통한 이메일 인증 오류로 인한 로직 변경
- RefreshToken Redis와 연동
close #125
> ✨ Feat : RefreshToken 구현

- src/main/java/com/hanghae/bulletbox/category/dto/ResponseCategoryDto.java
- src/main/java/com/hanghae/bulletbox/diary/entity/Diary.java
- src/main/java/com/hanghae/bulletbox/diary/repository/DiaryRepository.java
- src/main/java/com/hanghae/bulletbox/todo/controller/DailyController.java
- src/main/java/com/hanghae/bulletbox/todo/controller/MainController.java
- src/main/java/com/hanghae/bulletbox/todo/dto/CalendarDto.java
- src/main/java/com/hanghae/bulletbox/todo/dto/DailyDto.java
- src/main/java/com/hanghae/bulletbox/todo/dto/DailyTodoDto.java
- src/main/java/com/hanghae/bulletbox/todo/dto/RequestCreateTodoDto.java
- src/main/java/com/hanghae/bulletbox/todo/dto/RequestLoadFavoriteDto.java
- src/main/java/com/hanghae/bulletbox/todo/dto/RequestUpdateTodoDto.java
- src/main/java/com/hanghae/bulletbox/todo/dto/ResponseDailyDto.java
- src/main/java/com/hanghae/bulletbox/todo/dto/ResponseShowCalendarDto.java
- src/main/java/com/hanghae/bulletbox/todo/dto/ResponseShowDailyByCategoryDto.java
- src/main/java/com/hanghae/bulletbox/todo/dto/ResponseShowDailyDto.java
- src/main/java/com/hanghae/bulletbox/todo/dto/ResponseShowMainPageDto.java
- src/main/java/com/hanghae/bulletbox/todo/dto/ResponseShowTodoCreatePageDto.java
- src/main/java/com/hanghae/bulletbox/todo/dto/ResponseTodoUpdatePageDto.java
- src/main/java/com/hanghae/bulletbox/todo/dto/TodoDto.java
- src/main/java/com/hanghae/bulletbox/todo/service/DailyService.java
- src/main/java/com/hanghae/bulletbox/todo/service/DailyTodoService.java
- src/main/java/com/hanghae/bulletbox/todo/service/MainService.java
Diary Entity 생성 및 기존 Diary 패키지에 있던 내용들 Todo 패키지로 이동
close #149
> ✨ feat: Diary Entity 생성 및 패키지 구조 변경

- src/main/java/com/hanghae/bulletbox/todo/service/DailyTodoService.java
루틴 불러오기 API 호출 시, 발생하는 오류 수정
- 루틴의 메모가 존재하지 않을 경우 에러가 발생했었음.
- 해결 -> 루틴의 메모가 존재하지 않을 경우, 분기 로직 구현.
close #155
> 🐛 Fix: 루틴 불러오기 API 호출 시, 발생하는 오류 수정

- src/main/java/com/hanghae/bulletbox/diary/controller/DiaryController.java
- src/main/java/com/hanghae/bulletbox/diary/dto/DiaryDto.java
- src/main/java/com/hanghae/bulletbox/diary/dto/MonthlyEmotionDto.java
- src/main/java/com/hanghae/bulletbox/diary/dto/ResponseDiaryPageDto.java
- src/main/java/com/hanghae/bulletbox/diary/entity/Diary.java
- src/main/java/com/hanghae/bulletbox/diary/repository/DiaryRepository.java
- src/main/java/com/hanghae/bulletbox/diary/service/DiaryPageService.java
- src/main/java/com/hanghae/bulletbox/diary/service/DiaryService.java
일기장 페이지를 조회하는 API 구현하였습니다. 처음 들어왔을 때 달력에 표시하기 위해 이 달의 일기 중 감정이 있는 것들을 모두 가져와서 반환해 줍니다.
close #150
> ✨ feat: 일기장 페이지 조회 API 구현

- src/main/java/com/hanghae/bulletbox/todo/entity/Todo.java
- src/main/java/com/hanghae/bulletbox/todo/service/TodoService.java
할 일 API 호출 시, Todo가 삭제된 카테고리ID를 들고 있을 경우, 수정 전 카테고리 유효성 검사를 통과하지 못 해 오류 발생. (삭제된 카테고리는 member 에게 없기 때문)
- 클라이언트 요청으로부터 받아온 카테고리 ID 값으로 유효성 검사를 진행할 수 있도록 로직 수정.
close #158
> 🐛 Fix: 할 일 API 호출 시, 오류 발생 해결

- src/main/java/com/hanghae/bulletbox/favorite/entity/Favorite.java
- src/main/java/com/hanghae/bulletbox/favorite/service/FavoriteService.java
루틴 수정 시, 루틴의 카테고리가 삭제되었던 카테고리라면, 카테고리 유효성 검사를 통과하지 못 해 오류 발생. (삭제된 카테고리는 member가 가지고 있지 않기 때문)
- 클라이언트 요청으로부터 받은 카테고리 ID 를 통해 카테고리 유효성 검사를 진행할 수 있도록 로직 수정.
close #160
> 🐛 Fix: 루틴 수정 시, 발생하는 오류 해결

- src/main/java/com/hanghae/bulletbox/diary/controller/DiaryController.java
- src/main/java/com/hanghae/bulletbox/diary/dto/ResponseDiaryCalendarPageDto.java
- src/main/java/com/hanghae/bulletbox/diary/dto/ResponseDiaryPageDto.java
- src/main/java/com/hanghae/bulletbox/diary/service/DiaryPageService.java
- src/main/java/com/hanghae/bulletbox/diary/service/DiaryService.java
일기장 페이지 달력 조회 날짜를 변경하는 API를 구현하였습니다. 추가로 기존에 Transactional을 붙이지 않았던 메소드들에 Transactional 어노테이션을 붙여주었습니다.
close #151
> ✨ feat: 일기장 페이지 달력 조회 날짜 변경 API 구현

- scripts/start.sh
- scripts/stop.sh
배포 스크립트 수정
- 배포 스크립트 수정
close #163
> 🐛 Fix: 배포 스크립트 수정

- src/main/java/com/hanghae/bulletbox/diary/controller/DiaryController.java
- src/main/java/com/hanghae/bulletbox/diary/dto/DiaryDto.java
- src/main/java/com/hanghae/bulletbox/diary/repository/DiaryRepository.java
- src/main/java/com/hanghae/bulletbox/diary/service/DiaryPageService.java
- src/main/java/com/hanghae/bulletbox/diary/service/DiaryService.java
일기 조회 날짜를 변경하는 API를 구현하였습니다.
close #153
> ✨ feat: 일기 조회 날짜 변경 API 구현

- appspec.yml
- scripts/start.sh
> 🐛 Fix: 배포 스크립트 테스트

- src/main/java/com/hanghae/bulletbox/common/exception/ExceptionMessage.java
- src/main/java/com/hanghae/bulletbox/diary/controller/DiaryController.java
- src/main/java/com/hanghae/bulletbox/diary/dto/DiaryDto.java
- src/main/java/com/hanghae/bulletbox/diary/dto/RequestDiaryUpdateDto.java
- src/main/java/com/hanghae/bulletbox/diary/entity/Diary.java
- src/main/java/com/hanghae/bulletbox/diary/service/DiaryPageService.java
- src/main/java/com/hanghae/bulletbox/diary/service/DiaryService.java
일기장이 기존에 없었을 경우엔 생성하고, 있었을 경우엔 수정하는 API를 구현하였습니다.
close #152
> ✨ feat: 일기장 생성 및 수정 API 구현

- src/main/java/com/hanghae/bulletbox/todo/dto/ResponseShowDailyDto.java
- src/main/java/com/hanghae/bulletbox/todo/service/DailyService.java
프론트 렌더링을 위해 데일리 로그 날짜 변경 조회 시 응답 값에 카테고리 추가
close #175
> ✨ feat: 데일리 로그 날짜 변경 조회 시 응답값에 카테고리 추가

- src/main/java/com/hanghae/bulletbox/diary/controller/DiaryController.java
- src/main/java/com/hanghae/bulletbox/diary/service/DiaryPageService.java
- src/main/java/com/hanghae/bulletbox/diary/service/DiaryService.java
프론트 렌더링을 위해 일기장 작성/수정 시 해당 내용 반환하는 로직 추가
close #178
> ✨ feat: 일기장 작성/수정 시 해당 내용 반환하는 로직 추가

- scripts/deploy.sh
docker image name 소문자로 설정
- docker image name 소문자로 설정
> 🐛 Fix: docker image name 소문자로 변경

- .github/workflows/ci.yml
- Dockerfile
dockerfile, ci 파일 수정
- dockerfile, ci 파일 수정
> 🐛 Fix: dockerfile, ci 파일 수정

- .github/workflows/ci.yml
- Dockerfile
- scripts/deploy.sh
> 🐛 Fix: 도커 배포 테스트

- scripts/deploy.sh
docker 배포 테스트
docker 배포 테스트
close #177
> 🐛 Fix: docker 배포 테스트

- appspec.yml
- scripts/deploy.sh
도커 적용 완료로 인한 불필요한 코드 제거
- 도커 적용 완료로 인한 불필요한 코드 제거
close #188
> ♻️ Refactor: 도커 적용 완료로 인한 불필요한 코드 제거

- src/main/java/com/hanghae/bulletbox/category/controller/CategoryController.java
- src/main/java/com/hanghae/bulletbox/category/dto/CategoryDto.java
- src/main/java/com/hanghae/bulletbox/category/dto/ResponseCategoryDto.java
- src/main/java/com/hanghae/bulletbox/category/service/CategoryPageService.java
- src/main/java/com/hanghae/bulletbox/todo/controller/DailyController.java
- src/main/java/com/hanghae/bulletbox/todo/controller/MainController.java
- src/main/java/com/hanghae/bulletbox/todo/dto/CalendarDto.java
- src/main/java/com/hanghae/bulletbox/todo/dto/DailyDto.java
- src/main/java/com/hanghae/bulletbox/todo/dto/ResponseDailyDto.java
- src/main/java/com/hanghae/bulletbox/todo/service/DailyService.java
- src/main/java/com/hanghae/bulletbox/todo/service/MainService.java
- src/main/java/com/hanghae/bulletbox/todo/service/TodoMemoService.java
- src/main/java/com/hanghae/bulletbox/todo/service/TodoService.java
Todo 도메인에 속한 모든 API 리팩토링 진행.
- 반복되는 로직 메소드화 
- Repository에 직접 접하는 서비스 계층을 제외하곤 Entity 사용하지 않도록 수정 
- 서로 다른 서비스에서 중복되는 메소드는 그 둘이 공통적으로 사용하는 Facade 서비스의 메소드로 만들어서 사용.
close #180
> ♻️ refactor: Todo 도메인에 속한 모든 API 리팩토링 진행

- src/main/java/com/hanghae/bulletbox/diary/dto/DiaryDto.java
- src/main/java/com/hanghae/bulletbox/diary/service/DiaryService.java
일기장이 없는 날짜 조회 시 발생하던 오류 수정.
Optional을 확인하지 않고 get을 해서 문제가 발생했었음.
close #196
> 🐛 fix: 일기장이 없는 날짜 조회 시 발생하던 오류 수정

- .github/workflows/ci-cd.yml
- .github/workflows/ci.yml
merge 시, cd 오류 발생
- ci, cd 스크립트 수정
> 🐛 Fix: merge 시, cd 오류 발생

- .github/workflows/ci-cd.yml
> 🐛 Fix: CD 오류 수정

- .github/workflows/ci-cd.yml
cd uses or run key 에러 수정
- `-names 로직 ~` 밑에 -uses 로 -이 들어가 있어서 에러가 발생. -을 지워줌.
> 🐛 Fix: cd uses or run key 에러 수정

- .github/workflows/ci-cd.yml
> 🐛 Fix: cd 파일 수정

- .github/workflows/ci-cd.yml
> 🐛 Fix: cd 수정

- docker-compose.yml
docker-compose 파일 문법 수정
- docker-compose 파일 문법 수정
> 🐛 Fix: docker-compose 파일 문법 수정

- docker-compose.yml
docker-compose 파일 수정
- docker-compose 파일 수정
> 🐛 Fix: docker-compose 파일 수정

- docker-compose.yml
- src/main/resources/application.properties
docker-compose 파일 수정 및 redis host 수정
- docker-compose 파일 수정 및 redis host 수정
> 🐛 Fix: docker-compose 파일 수정 및 redis host 수정

- src/main/resources/application.properties
> 🐛 Fix: redis host 변경

- .github/workflows/ci-cd.yml
- src/main/resources/application.properties
cd, docker-compose 파일 수정
- cd, docker-compose 파일 수정
> 🐛 Fix: cd, docker-compose 파일 수정

- src/main/java/com/hanghae/bulletbox/todo/TodoBullet.java
- src/main/java/com/hanghae/bulletbox/todo/dto/TodoDto.java
TodoBullet Enum에 불렛 이름 추가
close #208
> ✨ feat: 불렛 이름 추가

- .github/workflows/ci-cd.yml
- .github/workflows/ci.yml
- build.gradle
- src/main/java/com/hanghae/bulletbox/member/controller/MemberController.java
- src/main/java/com/hanghae/bulletbox/member/entity/Member.java
- src/main/java/com/hanghae/bulletbox/member/service/KakaoService.java
- src/main/java/com/hanghae/bulletbox/member/type/SocialTypeEnum.java
- src/main/resources/application.properties
카카오 OAuth 구현
- 카카오 OAuth 구현
close #126
> ✨ Feat : 카카오 OAuth 구현

- .github/workflows/ci-cd.yml
- .github/workflows/ci.yml
- build.gradle
- src/main/java/com/hanghae/bulletbox/member/controller/MemberController.java
- src/main/java/com/hanghae/bulletbox/member/entity/Member.java
- src/main/java/com/hanghae/bulletbox/member/service/GoogleService.java
- src/main/java/com/hanghae/bulletbox/member/service/KakaoService.java
- src/main/java/com/hanghae/bulletbox/member/type/SocialTypeEnum.java
- src/main/resources/application.properties
구글 OAuth 구현
- 구글 OAuth 구현
close #127
> ✨ Feat : 구글 OAuth 구현

- src/main/resources/application.properties
application.properties 수정
- application.properties 수정
> 🐛 Fix: application.properties 수정

- .github/workflows/ci-cd.yml
> ♻️ Refactor: 개행 추가

- src/main/resources/application.properties
properties 파일 수정
- properties 파일 수정
> 🐛 Fix: properties 파일 수정

- src/main/resources/application.properties
properties 수정
- properties 수정
close #214
> ♻️ Refactor: properties 수정(버그 해결 완료)

- src/main/java/com/hanghae/bulletbox/category/controller/CategoryController.java
- src/main/java/com/hanghae/bulletbox/category/dto/CategoryDto.java
- src/main/java/com/hanghae/bulletbox/category/dto/ResponseCreateCategoryDto.java
- src/main/java/com/hanghae/bulletbox/category/dto/ResponseShowCategoryDto.java
- src/main/java/com/hanghae/bulletbox/category/entity/Category.java
- src/main/java/com/hanghae/bulletbox/category/service/CategoryPageService.java
- src/main/java/com/hanghae/bulletbox/category/service/CategoryService.java
- src/main/java/com/hanghae/bulletbox/common/exception/ExceptionMessage.java
- src/main/java/com/hanghae/bulletbox/todo/TodoBullet.java
Category 도메인에 있는 모든 API 리팩토링 진행. Repository와 직접 접하는 서비스 외에 Entity 사용하지 않도록 수정. 반복되는 로직 메소드화.
close #209
> ♻️ refactor: Category 도메인에 있는 모든 API 리팩토링

- src/main/java/com/hanghae/bulletbox/member/controller/MemberController.java
- src/main/java/com/hanghae/bulletbox/member/service/MemberService.java
Test용 로그인 구현
- Test용 로그인 구현
close #128 
> ✨ Feat : Test용 로그인 구현

- src/main/java/com/hanghae/bulletbox/category/service/CategoryService.java
- src/main/java/com/hanghae/bulletbox/favorite/entity/Favorite.java
- src/main/java/com/hanghae/bulletbox/favorite/repository/FavoriteRepository.java
- src/main/java/com/hanghae/bulletbox/todo/entity/Todo.java
- src/main/java/com/hanghae/bulletbox/todo/repository/TodoRepository.java
카테고리 삭제 시 해당 카테고리를 사용하던 Todo와 favorite의 카테고리 값들 null로 변경
close #220
> 🐛 fix: 카테고리 삭제 시 해당 카테고리를 사용하던 Todo와 favorite의 카테고리 값들 null로 변경

- src/main/java/com/hanghae/bulletbox/member/controller/MemberController.java
- src/main/java/com/hanghae/bulletbox/member/dto/MemberDto.java
- src/main/java/com/hanghae/bulletbox/member/dto/ResponseFirstLoginDto.java
- src/main/java/com/hanghae/bulletbox/member/dto/ResponseLoginDto.java
- src/main/java/com/hanghae/bulletbox/member/entity/Member.java
- src/main/java/com/hanghae/bulletbox/member/service/MemberService.java
첫번째 로그인 여부 확인 로직 추가
- 첫번째 로그인 여부 확인 로직 추가
close #223
> ✨ Feat : 첫번째 로그인 여부 확인 로직 추가

- src/main/java/com/hanghae/bulletbox/member/entity/Member.java
회원가입 시 firstLogin 값 true로 되도록 변경
close #225
> 🐛 fix: 회원가입 시 발생하는 500에러 수정

- src/main/java/com/hanghae/bulletbox/diary/controller/DiaryController.java
- src/main/java/com/hanghae/bulletbox/diary/service/DiaryPageService.java
일기장 수정, 삭제 시 그 달의 emotion 리스트로 반환하도록 변경
close #227
> ✨ feat: 일기장 수정, 삭제 시 그 달의 emotion 리스트로 반환하도록 변경

- src/main/java/com/hanghae/bulletbox/member/service/MemberService.java
체험하기 로그인  non null key required 오류 수정
- 체험하기 로그인  non null key required 오류 수정
close #229
> 🐛 Fix : 체험하기 로그인  non null key required 오류 수정

- scripts/deploy.sh
카카오 로그인 시, KOE 303 에러 수정
- 쉘 스크립트에 개행 추가 ( 커밋을 위해)
- github secret의 OAUTH 코드 수정
> 🐛 Fix: 카카오 로그인 시, KOE 303 에러 수정

- src/main/java/com/hanghae/bulletbox/member/controller/MemberController.java
- src/main/java/com/hanghae/bulletbox/member/service/GoogleService.java
- src/main/java/com/hanghae/bulletbox/member/service/KakaoService.java
카카오, 구글 OAuth 첫번째 로그인 여부 확인 로직 추가
- 카카오, 구글 OAuth 첫번째 로그인 여부 확인 로직 추가
close #233 
> ✨ Feat : 카카오, 구글 OAuth 첫번째 로그인 여부 확인 로직 추가

- src/main/java/com/hanghae/bulletbox/member/controller/MemberController.java
- src/main/java/com/hanghae/bulletbox/member/dto/MemberDto.java
- src/main/java/com/hanghae/bulletbox/member/entity/Member.java
- src/main/java/com/hanghae/bulletbox/member/service/GoogleService.java
- src/main/java/com/hanghae/bulletbox/member/service/KakaoService.java
첫번째 로그인 true/false 수정
- 첫번째 로그인 true/false 수정
close #235
> 🐛 Fix : 첫번째 로그인 true/false 수정

- src/main/java/com/hanghae/bulletbox/member/entity/Member.java
- src/main/java/com/hanghae/bulletbox/member/service/GoogleService.java
- src/main/java/com/hanghae/bulletbox/member/service/KakaoService.java
카카오 구글 OAuth setFirstLogin로직 추가
- 카카오 구글 OAuth setFirstLogin로직 추가
close #237
> 🐛 Fix : 카카오 구글 OAuth setFirstLogin로직 추가

- src/main/java/com/hanghae/bulletbox/todo/entity/Todo.java
할 일 수정 시 time 수정내용 반영
close #239
> 🐛 fix: 할 일 수정 시 time 수정내용 반영

- src/main/java/com/hanghae/bulletbox/favorite/dto/ResponseCreateFavoriteTodoDto.java
- src/main/java/com/hanghae/bulletbox/favorite/service/FavoritePageService.java
루틴 생성 시 카테고리 정보 반환하는 로직 추가
close #241
> ✨ feat: 루틴 생성 시 카테고리 정보 반환하는 로직 추가

- src/main/java/com/hanghae/bulletbox/common/config/WebSecurityConfig.java
- src/main/java/com/hanghae/bulletbox/common/security/jwt/JwtAuthenticationFilter.java
- src/main/java/com/hanghae/bulletbox/common/security/jwt/JwtUtil.java
- src/main/java/com/hanghae/bulletbox/common/security/jwt/exception/JwtExceptionHandlerFilter.java
시큐리티 적용
- 프론트 작업의 수월함을 위해 열어두었던 시큐리티를 다시 적용.
close #243
> ♻️ Refactor: 시큐리티 적용

- src/main/java/com/hanghae/bulletbox/member/controller/MemberController.java
Oauth properties 값 수정
close #245
> 🐛 fix: Oauth properties 값 수정

- build.gradle
- src/main/java/com/hanghae/bulletbox/member/service/GoogleService.java
- src/main/java/com/hanghae/bulletbox/member/service/KakaoService.java
구글 로그인 RestTemplate 이슈 수정
- 구글 로그인 RestTemplate 이슈 수정
close #249
> 🐛 Fix: 구글 로그인 RestTemplate 이슈 수정

- src/main/java/com/hanghae/bulletbox/todo/entity/Todo.java
날짜가 반영 안되게 되어 있었음. 해당 부분 수정
Todo 업데이트 메소드 수정
close #254
> 🐛 fix: Todo 업데이트 메소드 수정

- src/main/java/com/hanghae/bulletbox/common/config/WebSecurityConfig.java
Security config에 프론트 배포 주소 추가
close #257
> ✨ feat: Security config에 프론트 배포 주소 추가

- .github/workflows/ci-cd.yml
- scripts/deploy.sh
- src/main/java/com/hanghae/bulletbox/favorite/controller/FavoriteController.java
- src/main/java/com/hanghae/bulletbox/favorite/dto/ResponseUpdateFavoriteDto.java
- src/main/java/com/hanghae/bulletbox/favorite/service/FavoriteMemoService.java
- src/main/java/com/hanghae/bulletbox/favorite/service/FavoritePageService.java
- src/main/java/com/hanghae/bulletbox/favorite/service/FavoriteService.java
- src/main/resources/application.properties
루틴 수정 시, 응답 값 출력하도록 수정
- 루틴 수정 시, 응답 값 출력하도록 수정
close #253
> ♻️ Refactor: 루틴 수정 시, 응답 값 출력하도록 수정

- .github/workflows/ci-cd.yml
- scripts/deploy.sh
- src/main/resources/application.properties
docker compose redis 수정
- docker compose 로 레디스 실행 후 테스트 예정
> 🐛 Fix: docker compose redis 수정

- src/main/java/com/hanghae/bulletbox/common/config/WebSecurityConfig.java
Security config에 프론트 배포 주소 추가
close #262
> 🐛 fix: Security config에 프론트 배포 주소 추가

- src/main/java/com/hanghae/bulletbox/common/config/WebSecurityConfig.java
> 🐛 Fix: 스웨거 path 수정

- src/main/java/com/hanghae/bulletbox/member/entity/Member.java
- src/main/java/com/hanghae/bulletbox/member/service/GoogleService.java
- src/main/java/com/hanghae/bulletbox/member/service/KakaoService.java
- src/main/java/com/hanghae/bulletbox/member/service/MemberService.java
- src/main/java/com/hanghae/bulletbox/todo/dto/ResponseShowMainPageDto.java
- src/main/java/com/hanghae/bulletbox/todo/service/MainService.java
메인 페이지 조회 시 첫 로그인 여부 반환
close #265
> 🐛 fix: 메인 페이지 조회 시 첫 로그인 여부 반환

- src/main/java/com/hanghae/bulletbox/todo/dto/SearchTodoDto.java
- src/main/java/com/hanghae/bulletbox/todo/entity/Todo.java
TodoBullet Enum 의 Name 값을 응답하도록 로직 수정
- TodoBullet Enum 의 Name 값을 응답하도록 로직 수정
close #255
> ♻️ Refactorr: TodoBullet Enum 의 Name 값을 응답하도록 로직 수정

- src/main/java/com/hanghae/bulletbox/favorite/service/FavoritePageService.java
내용을 적어주세요.
- 루틴 생성 시, 삭제된 MemoId 값을 응답하지 않도록 수정
close #268
> ♻️ Refactor: 루틴 생성 시, 삭제된 MemoId 값을 응답하지 않도록 수정

- .github/workflows/ci-cd.yml
- docker-compose.blue.yml
- docker-compose.green.yml
- scripts/deploy.sh
Nginx + Docker 를 활용한 무중단 배포 테스트
- Nginx + Docker 를 활용한 무중단 배포 테스트
> ✨ Feat: Nginx + Docker 를 활용한 무중단 배포 테스트

- scripts/deploy.sh
배포 스크립트 실행 시, 도커 컴포즈로 실행된 모든 컨테이너가 종료되지 않는 현상 발생
- docker-compose down 로직 추가하여 도커 컴포즈로 띄워진 컨테이너 모두 종료 시킴
close #277
> 🐛 Fix: 배포 스크립트 실행 시, 도커 컴포즈로 실행된 모든 컨테이너가 종료되지 않는 현상 발생

- appspec.yml
배포 스크립트가 정상 작동이 안 되는 오류 발생
- CodeDeploy 시, appspec의 이벤트 후크가 정상 작동이 안 됨. - ApplicationStart 후크에서 AfterInstall 후크로 변경
close #284
> 🐛 Fix: 배포 스크립트가 정상 작동이 안 되는 오류 발생

- appspec.yml
- deploy.sh
- scripts/deploy.sh
> 🐛 Fix: 배포 스크립트 위치 수정

- .github/workflows/ci-cd.yml
- scripts/deploy.sh
ci-cd 코드 원상 복구
- codedeploy 를 활용하지 않고 github actions 를 통해 docker-compose 실행.
close #284
> 🐛 Fix: ci-cd 코드 원상 복구

- .github/workflows/ci-cd.yml
github actions ci-cd 파일 수정
- github actions ci-cd 파일 수정
close #284
> 🐛 Fix: github actions ci-cd 파일 수정

- src/main/java/com/hanghae/bulletbox/category/service/CategoryPageService.java
- src/main/java/com/hanghae/bulletbox/category/service/CategoryService.java
카테고리 생성 시, 생성이 안 되는 오류 수정
- 카테고리 생성 시, 수정과 같은 중복 검사 로직을 사용하다보니 오류가 발생함.
- 수정 외에 사용하는 로직을 따로 만듦.
close #290
> 🐛 Fix: 카테고리 생성 시, 생성이 안 되는 오류 수정

- src/main/java/com/hanghae/bulletbox/category/dto/ResponseCategoryDto.java
- src/main/java/com/hanghae/bulletbox/daily/controller/DailyController.java
- src/main/java/com/hanghae/bulletbox/daily/dto/DailyDto.java
- src/main/java/com/hanghae/bulletbox/daily/dto/DailyTodoDto.java
- src/main/java/com/hanghae/bulletbox/daily/dto/RequestCreateTodoDto.java
- src/main/java/com/hanghae/bulletbox/daily/dto/RequestLoadFavoriteDto.java
- src/main/java/com/hanghae/bulletbox/daily/dto/RequestUpdateTodoDto.java
- src/main/java/com/hanghae/bulletbox/daily/dto/ResponseDailyDto.java
- src/main/java/com/hanghae/bulletbox/daily/dto/ResponseLoadFavoriteDto.java
- src/main/java/com/hanghae/bulletbox/daily/dto/ResponseShowTodoCreatePageDto.java
- src/main/java/com/hanghae/bulletbox/daily/dto/ResponseTodoUpdatePageDto.java
- src/main/java/com/hanghae/bulletbox/daily/service/DailyService.java
- src/main/java/com/hanghae/bulletbox/daily/service/DailyTodoService.java
- src/main/java/com/hanghae/bulletbox/main/controller/MainController.java
- src/main/java/com/hanghae/bulletbox/main/dto/CalendarDto.java
- src/main/java/com/hanghae/bulletbox/main/dto/ResponseShowCalendarDto.java
- src/main/java/com/hanghae/bulletbox/main/dto/ResponseShowDailyByCategoryDto.java
- src/main/java/com/hanghae/bulletbox/main/dto/ResponseShowDailyDto.java
- src/main/java/com/hanghae/bulletbox/main/dto/ResponseShowMainPageDto.java
- src/main/java/com/hanghae/bulletbox/main/service/MainService.java
- src/main/java/com/hanghae/bulletbox/todo/dto/TodoDto.java
- src/main/java/com/hanghae/bulletbox/todo/service/TodoMemoService.java
프로젝트 패키지 재구조화
- 프로젝트 패키지 재구조화
close #292
> 🔧 Chore: 프로젝트 패키지 재구조화

- src/main/java/com/hanghae/bulletbox/favorite/dto/FavoriteMemoDto.java
내용을 적어주세요.
- favoriteMemoId, favoriteMemoContent 로 멤버변수명 변경
close #295
> 🐛 Fix: 루틴 수정 시, 요청 온 루틴의 메모 ID 와 응답한 루틴의 메모 ID 불일치한 오류 해결

- src/main/java/com/hanghae/bulletbox/diary/entity/Diary.java
- src/main/java/com/hanghae/bulletbox/favorite/entity/Favorite.java
- src/main/java/com/hanghae/bulletbox/favorite/entity/FavoriteMemo.java
- src/main/java/com/hanghae/bulletbox/main/service/MainService.java
- src/main/java/com/hanghae/bulletbox/member/controller/MemberController.java
- src/main/java/com/hanghae/bulletbox/member/dto/MemberDto.java
- src/main/java/com/hanghae/bulletbox/member/entity/Member.java
- src/main/java/com/hanghae/bulletbox/member/repository/MemberRepository.java
- src/main/java/com/hanghae/bulletbox/member/service/AuthService.java
- src/main/java/com/hanghae/bulletbox/member/service/GoogleService.java
- src/main/java/com/hanghae/bulletbox/member/service/KakaoService.java
- src/main/java/com/hanghae/bulletbox/member/service/MailService.java
- src/main/java/com/hanghae/bulletbox/member/service/MemberService.java
Member 도메인에 Facade 패턴을 적용하였습니다. 
기존 MemberService는 AuthService로 바꾸고, Repository에 접하는 MemberService를 새로 만들었습니다.
반복되는 로직은 메소드화 시켰습니다.
close #294
> ♻️ refactor: Member 도메인 리팩토링

- src/main/java/com/hanghae/bulletbox/member/entity/Member.java
- src/main/java/com/hanghae/bulletbox/member/repository/MemberRepository.java
- src/main/java/com/hanghae/bulletbox/member/service/AuthService.java
- src/main/java/com/hanghae/bulletbox/member/service/MemberService.java
matches 메소드를 사용하도록 로직 변경
로그인 시 비밀번호 검증 오류 해결. 비밀번호 검증 시 matches 메소드를 사용하도록 변경
close #298
> 🐛 fix: 로그인 시 비밀번호 검증 오류 해결
